//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html

using System;

namespace PrintApp
{
    
    
    public partial class table1
    {
        public Int32? colum { get; set; }
        
    }
    
}
